name: Jekyll publication on GitHub Pages

on:
  push:
    branches:
      - "dev"
    paths:
      - "jekyll/**"
      - ".github/workflows/ghpages.yml"
  workflow_dispatch:

jobs:
  jekyll:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: "github"
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "informalsystems/modelator"
          branch: "gh-pages"
          jekyll_src: "./jekyll"
          jekyll_cfg: "_config.yml"
          bundler_ver: ">=0"
          cname: "mbt.informal.systems"
