name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      update_component:
        description: "Release component (eg. major, minor, patch)"
        required: false
        default: patch

jobs:
  prepare-release:
    environment: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Verify and generate version
        env:
          UPDATE_COMPONENT: ${{ github.event.inputs.update_component }}
        run: |
          ./scripts/generate_version.sh "${UPDATE_COMPONENT}"

      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "github@actions.ci"

      - name: Install `quickinstall`
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-quickinstall

      - name: Install `unclog`
        uses: actions-rs/cargo@v1
        with:
          command: quickinstall
          args: unclog

      - name: Prepare release branch
        run: |
          ./scripts/prepare_release.sh

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Poetry publish
        run: |
          poetry publish --username u --password p --build --dry-run
